name: build dist

on:
  workflow_call:

jobs:
  linux-build:
    if: false
    name: build on linux
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: apt update
      run: |
        sudo apt-get update
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
    - name: set up node
      uses: actions/setup-node@v4
      if: ${{ vars.AAP_JUCE_NODE_VERSION != '' }}
      with:
        node-version: ${{ vars.AAP_JUCE_NODE_VERSION }}
    - name: cache AVD
      uses: actions/cache@v4
      env:
        cache-name: cache-avd
      with:
        path: /home/runner/.android/gradle/avd
        key: ${{ runner.os }}-gradle-avd
    - name: cache gradle caches
      uses: actions/cache@v4
      env:
        cache-name: cache-gradle-caches
      with:
        path: /home/runner/.gradle/caches/
        key: ${{ runner.os }}-gradle-caches
    - name: apt install
      run: |
        echo y | sudo apt-get install xvfb wget unzip libc6 \
                 libcurl3-gnutls-dev  libfreetype6-dev libgcc1 libjpeg-dev \
                 libpng-dev libwebkit2gtk-4.1-dev libx11-6 \
                 libxext6 zlib1g  make g++ mesa-common-dev libasound2-dev \
                 libjack-jackd2-dev ladspa-sdk doxygen \
                 graphviz cmake ninja-build
    - name: build
      run: make build dist

  osx-build:
    name: build on osx
    runs-on: macos-14
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
    - name: cache AVD
      uses: actions/cache@v4
      env:
        cache-name: cache-avd
      with:
        path: /Users/runner/.android/gradle/avd
        key: ${{ runner.os }}-gradle-avd
    - name: cache gradle caches
      uses: actions/cache@v4
      env:
        cache-name: cache-gradle-caches
      with:
        path: /Users/runner/.gradle/caches/
        key: ${{ runner.os }}-gradle-caches
    - name: install deps
      run: |
        brew install doxygen pkg-config cmake coreutils ninja graphviz
    - name: build
      run: make build dist
    - name: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist
    - name: Create Release
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        artifacts: dist/*
