name: build dist

on:
  workflow_call:

jobs:
  linux-build:
    name: build on linux
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: apt update
      run: |
        sudo apt-get update
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin
    - name: cache AVD
      uses: actions/cache@v3
      env:
        cache-name: cache-avd
      with:
        path: /home/runner/.android/gradle/avd
        key: ${{ runner.os }}-gradle-avd
    - name: cache gradle caches
      uses: actions/cache@v3
      env:
        cache-name: cache-gradle-caches
      with:
        path: /home/runner/.gradle/caches/
        key: ${{ runner.os }}-gradle-caches
    - name: apt install
      run: |
        echo y | sudo apt-get install xvfb wget unzip libc6 \
                 libcurl3-gnutls-dev  libfreetype6-dev libgcc1 libjpeg-dev \
                 libpng-dev libstdc++6 libwebkit2gtk-4.0-dev libx11-6 \
                 libxext6 zlib1g  make g++ mesa-common-dev libasound2-dev \
                 libjack-jackd2-dev ladspa-sdk doxygen \
                 graphviz cmake ninja-build
    - name: build
      run: xvfb-run -a --server-args="-screen 0 1280x800x24 -ac -nolisten tcp -dpi 96 +extension RANDR" make MINIMIZE_INTERMEDIATES=1 build dist
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      if: startsWith(github.ref, 'refs/tags/')
      with:
        artifacts: dist/*

  osx-build:
    name: build on osx
    runs-on: macos-12
    if: false
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin
    - name: cache AVD
      uses: actions/cache@v3
      env:
        cache-name: cache-avd
      with:
        path: /Users/runner/.android/gradle/avd
        key: ${{ runner.os }}-gradle-avd
    - name: cache gradle caches
      uses: actions/cache@v3
      env:
        cache-name: cache-gradle-caches
      with:
        path: /Users/runner/.gradle/caches/
        key: ${{ runner.os }}-gradle-caches
    - name: install deps
      run: |
        brew install doxygen pkg-config cmake coreutils ninja graphviz
    - name: build
      run: make MINIMIZE_INTERMEDIATES=1 build dist
      env:
        ANDROID_SDK_ROOT: /Users/runner/Library/Android/sdk
